// Glossary data — the single source of truth for the report's terminology.
// Each entry is one dictionary term: an `id` (used for deep-linking from the
// inline "book-open" buttons), the visible `term`, an optional short gloss
// shown in the list, the full `definition`, and any external `sources`.
//
// `id`s match what `slugify` produces for the term, so an inline trigger can
// pass either the id or the term text and still resolve the right entry.

export interface GlossarySource {
  label: string
  href: string
}

export interface GlossaryTerm {
  id: string
  term: string
  /** One-line gloss shown under the term in the list. */
  short: string
  /** Full definition (paragraphs split on blank lines). */
  definition: string
  sources?: GlossarySource[]
}

// Authored unsorted; `glossaryTerms` exposes them alphabetically.
const terms: GlossaryTerm[] = [
  {
    id: 'confidence-level',
    term: 'Confidence Level',
    short: 'Low / medium / high confidence in a given Node42 output.',
    definition:
      'Confidence level in our context describes whether a specific output generated by Node42 has a low, medium, or high confidence. An insight might be highly interesting but come with a low confidence level — it therefore requires additional validation.',
  },
  {
    id: 'core-functional-job',
    term: 'Core Functional Job',
    short: 'The single overarching goal a customer is trying to accomplish.',
    definition:
      'A core functional job (CFJ) is the single, overarching goal a customer is ultimately trying to accomplish for a specific problem. The CFJ is phrased functionally, along its task-completion dimension, not along identity or emotion. It is solution-agnostic and serves as the anchor for all Core Jobs, Emotional Jobs, and Social Jobs associated with the customer problem.\n\nSources: W. Scott Burleson, The Jobs-to-be-Done Pyramid: An Innovation Architecture for Humans — Linking Functions, Emotion, and Identity (The AIM Institute, 2025); Anthony W. Ulwick, Jobs to be Done: Theory to Practice (Idea Bite Press, 2016).',
  },
  {
    id: 'core-jobs',
    term: 'Core Jobs',
    short: 'Solution-agnostic goals that feed into the core functional job.',
    definition:
      'Core jobs are the solution-agnostic goals a customer is trying to accomplish — independent of any particular product or service solution. Per customer problem there is only 1 core functional job, but there are several core jobs connecting into it. If the core functional job sits at level 1 defining the overall problem (get me from A to B safely and economically), then the core jobs provide more detail to that (Reduce the need to stop along the way; Reduce the need to re-power along the way; Increase my flexibility to stop where I want at my destination; etc.).\n\nSources: W. Scott Burleson, The Jobs-to-be-Done Pyramid: An Innovation Architecture for Humans — Linking Functions, Emotion, and Identity (The AIM Institute, 2025); Anthony W. Ulwick, Jobs to be Done: Theory to Practice (Idea Bite Press, 2016).',
  },
  {
    id: 'emotional-jobs',
    term: 'Emotional Jobs',
    short: 'How a customer wants to feel when using a product or service.',
    definition:
      'Emotional jobs are the immediate feelings a customer wants to experience in the moment of interacting with a product or service — how they want to feel right then, rather than what they want to accomplish.\n\nSources: W. Scott Burleson, The Jobs-to-be-Done Pyramid: An Innovation Architecture for Humans — Linking Functions, Emotion, and Identity (The AIM Institute, 2025); Anthony W. Ulwick, Jobs to be Done: Theory to Practice (Idea Bite Press, 2016).',
  },
  {
    id: 'social-jobs',
    term: 'Social Jobs',
    short: 'How a customer wants to be perceived by others when using it.',
    definition:
      'Social jobs are about how a customer wants to be perceived by other people when they use a product or service — how they look to others.\n\nSources: W. Scott Burleson, The Jobs-to-be-Done Pyramid: An Innovation Architecture for Humans — Linking Functions, Emotion, and Identity (The AIM Institute, 2025); Anthony W. Ulwick, Jobs to be Done: Theory to Practice (Idea Bite Press, 2016).',
  },
  {
    id: 'constraint',
    term: 'Constraint',
    short: 'A limitation that comes with a product or service.',
    definition:
      'A constraint describes the limitations that come with a product or service. For example, a medical CT scanner has the constraint that the patient is exposed to radiation — which leads to the exclusion of certain use cases/market segments.',
  },
  {
    id: 'esco-code',
    term: 'ESCO Code',
    short: 'European skills, competences & occupations classification.',
    definition:
      'An ESCO code (European Skills, Competences, Qualifications and Occupations) is an identifier published by the European Commission for the building blocks of the EU labour market. It classifies 3,039 occupations and 13,939 skills linked to those occupations. It allows for apples-to-apples comparison of jobs and skills across countries, languages, and platforms irrespective of local job titles or national wording.',
    sources: [{ label: 'ec.europa.eu/esco', href: 'https://esco.ec.europa.eu/en' }],
  },
  {
    id: 'functional-promise',
    term: 'Functional Promise',
    short: 'The core job the product commits to performing.',
    definition:
      'A functional promise is the general value proposition of a product or service independent of which market it is sold into.',
  },
  {
    id: 'market',
    term: 'Market',
    short: 'People or organizations trying to get a specific job done.',
    definition:
      'A market is a set of people or organizations trying to get a specific job done defined by the outcomes they want to achieve — not by the product category, technology, or industry vertical that currently serves them. NAICS codes can be used to practically identify markets.\n\nSources: Anthony W. Ulwick, Jobs to be Done: Theory to Practice (Idea Bite Press, 2016); Clayton M. Christensen, Taddy Hall, Karen Dillon & David S. Duncan, Competing Against Luck (HarperBusiness, 2016).',
  },
  {
    id: 'market-attractiveness',
    term: 'Market Attractiveness',
    short: 'Composite score of a market’s opportunity size and fit.',
    definition:
      'Market Attractiveness is the composite score Node42 assigns to each suggested market, blending demand size, growth, competitive intensity and fit with the product’s Functional Promise. It is the ranking signal behind the "how attractive are these?" half of the report’s initial question.',
  },
  {
    id: 'naics-code',
    term: 'NAICS Code',
    short: 'North American Industry Classification System code.',
    definition:
      'A NAICS code (North American Industry Classification System) is a globally used identifier to classify industries and businesses by their primary economic activity. It helps track economic data, target B2B markets, and qualify for government contracts. It allows to define markets and align on their scope.',
    sources: [{ label: 'naics.com', href: 'https://www.naics.com/' }],
  },
  {
    id: 'odi',
    term: 'ODI',
    short: 'Outcome-Driven Innovation (Jobs-to-be-Done framework).',
    definition:
      'ODI is a term originating from Anthony Ulwick’s “Jobs-to-be-Done” framework. ODI stands for Outcome-Driven Innovation.\n\nSource: Anthony W. Ulwick, Jobs to be Done: Theory to Practice (Idea Bite Press, 2016).',
  },
  {
    id: 'problem-statement',
    term: 'Problem Statement',
    short: 'The Who / What / Why framing of the core challenge.',
    definition:
      'A structured breakdown of the core challenge the report addresses, expressed as three rows — Who is affected, What the problem is, and Why it matters. It frames every downstream analysis and keeps the scope honest.',
  },
  {
    id: 'sam',
    term: 'SAM',
    short: 'Serviceable Addressable Market — the reachable portion of TAM.',
    definition:
      'SAM stands for “Serviceable Addressable Market”, the portion of the TAM (Total Addressable Market) a product or service can reach given its business model, product, global reach, etc.',
  },
  {
    id: 'tam',
    term: 'TAM',
    short: 'Total Addressable Market — the full revenue opportunity.',
    definition:
      'TAM stands for “Total Addressable Market”, the total revenue opportunity available for a product or service.',
  },
  {
    id: 'value-network',
    term: 'Value Network',
    short: 'The full ecosystem within a market required to produce its output.',
    definition:
      'A value network in our context is the entire ecosystem within a market required to produce the market output. Think of the market as one big, virtual company that has all the processes, departments, machines, services, raw materials, etc. to produce the market output. The market output may be "a car", "a management consulting service", or "an oncology drug". The different parts may be "diagnostics" or "patient admission" for a hospital market, or it could be "research & development" or “HVAC and clean room” for a pharma manufacturing market. And so forth. Our definition cannot be found in one individual source. It is mainly derived from Clayton Christensen’s “The Innovator’s Dilemma” and Felix Oberholzer-Gee’s “Better Simpler Strategy”.\n\nSources: Clayton M. Christensen, The Innovator’s Solution: When New Technologies Cause Great Firms to Fail (Harvard Business School Press, 1997); Felix Oberholzer-Gee, Better, Simpler Strategy: A Value-Based Guide to Exceptional Performance (Harvard Business Review Press, 2021).',
  },
  {
    id: 'unspsc-code',
    term: 'UNSPSC Code',
    short: 'United Nations product & service taxonomy code.',
    definition:
      'A UNSPSC code (United Nations Standard Products and Services Code) is a globally used identifier for over 75,000 groups of products or services that share a common use or function. It allows for apples-to-apples comparison across products irrespective of their brand name.',
    sources: [{ label: 'unspsc.org', href: 'https://www.unspsc.org/' }],
  },
]

/** All terms, sorted alphabetically by `term` (locale-aware). */
export const glossaryTerms: GlossaryTerm[] = [...terms].sort((a, b) =>
  a.term.localeCompare(b.term),
)

/** Resolve a deep-link key (an id or a term label) to a glossary entry. */
export function findTerm(key: string | undefined): GlossaryTerm | undefined {
  if (!key) return undefined
  const k = key.toLowerCase()
  return glossaryTerms.find(
    (t) => t.id === k || t.term.toLowerCase() === k,
  )
}
